Feature/ QuantityPicker implementation, EditTextField update
dondoapp/dondo_ui_android pull request #6
Opened 2022-05-12 16:12 UTC by alejandro-rios

- QuantityPicker component moved to library.
- Fix on QuantityPicker crash for bigger values.
- EditTextField component updated with multiline choice.

https://user-images.githubusercontent.com/10689052/168120667-1c94b1d1-5e80-47eb-b563-9486fa6a84fb.mov

2022-05-16 12:37 UTC, ccparram requested changes

2022-05-16 12:37 UTC, ccparram commented on ui/src/main/java/com/dondo/ui/formfields/EditTextField.kt
> +            }
add else removing the filter.

2022-05-17 13:01 UTC, ccparram commented on ui/src/main/java/com/dondo/ui/quantitypicker/QuantityPicker.kt
> +    private val editableQuantity: AppCompatEditText = binding.etQuantity
Maybe etQuantity instead of editableQuantity?

2022-05-17 13:03 UTC, ccparram commented on ui/src/main/java/com/dondo/ui/quantitypicker/QuantityPicker.kt
> +        handleAttrs(attrs)
The standar is    setupAttrs(attrs)

2022-05-17 13:04 UTC, ccparram commented on ui/src/main/java/com/dondo/ui/quantitypicker/QuantityPicker.kt
> +        val styles: TypedArray = context.theme.obtainStyledAttributes(attrs, R.styleable.QuantityPicker, 0, 0)
Isn't shorter  context.theme.obtainStyledAttributes(it, R.styleable.EditTextField, 0, 0).apply {
?

2022-05-17 13:09 UTC, ccparram commented on ui/src/main/java/com/dondo/ui/quantitypicker/QuantityPicker.kt
> +        if (quantity != maxValue) quantity++
Please use {}
```suggestion
        if (quantity != maxValue) {
            quantity++
        }
```

2022-05-17 13:09 UTC, ccparram commented on ui/src/main/java/com/dondo/ui/quantitypicker/QuantityPicker.kt
> +        if (quantity != minValue) quantity--
Please use {}
```suggestion
        if (quantity != minValue) {
            quantity--
        }
```

2022-05-17 13:12 UTC, ccparram commented on ui/src/main/java/com/dondo/ui/quantitypicker/QuantityPicker.kt
> +                    ivPositive.setVisibility(!hasFocus)
```suggestion
                    ivNegative.isVisible = !hasFocus
                    ivPositive.isVisible =!hasFocus
```

2022-05-17 13:14 UTC, ccparram commented on ui/src/main/java/com/dondo/ui/quantitypicker/QuantityPicker.kt
> +    private fun setNumericalConstraints() {
We should put the inputType it directly in the xml.

2022-05-17 13:25 UTC, ccparram commented on ui/src/main/java/com/dondo/ui/utils/EditTexFieldType.kt
> +enum class EditTexFieldType(val value: Int) {
Delete class

2022-05-17 13:58 UTC, alejandro-rios commented on ui/src/main/java/com/dondo/ui/quantitypicker/QuantityPicker.kt
> +        handleAttrs(attrs)
Done

2022-05-17 14:00 UTC, alejandro-rios commented on ui/src/main/java/com/dondo/ui/quantitypicker/QuantityPicker.kt
> +        if (quantity != maxValue) quantity++
Done

2022-05-17 14:00 UTC, alejandro-rios commented on ui/src/main/java/com/dondo/ui/quantitypicker/QuantityPicker.kt
> +                    ivPositive.setVisibility(!hasFocus)
Done

2022-05-17 14:19 UTC, alejandro-rios commented on ui/src/main/java/com/dondo/ui/quantitypicker/QuantityPicker.kt
> +    private fun setNumericalConstraints() {
Done

2022-05-17 14:30 UTC, alejandro-rios commented on ui/src/main/java/com/dondo/ui/quantitypicker/QuantityPicker.kt
> +    private val editableQuantity: AppCompatEditText = binding.etQuantity
Done

2022-05-17 15:38 UTC, merged